### ISSUE TITLE
不能自动进入考试

### ISSUE THREAD

**Issue by hnzyc** [hysbeta/91huayi#4]
昨晚开了一晚上，发现只能反复播放同一个课，应该是视频播放完成之后，不会自动进入考试。
早上起来点击考试，后面的流程就可以，自动考试，自动交卷，更正重新进入下一课，这些都没问题，请看看怎么回事，是我使用方式有问题还是bug？

**Comment by hysbeta** [comment]
上的是公需课还是选修课 课名发一下我看看

**Comment by hysbeta** [comment]
修好了 更新91huayi_auto_class试试

**Comment by hnzyc** [comment]
感谢，我是公需课，测试下已经可以自动下一课了，简直太牛了。
另外想问下，视频播放窗口必须为当前页面才可以吗？有没有办法在后台也可以自动播放和考试呢？

**Comment by hysbeta** [comment]
这个我也不会耶，是浏览器的行为，只要当前页面不活动一段时间就会被静止。我一般是开虚拟机挂的，可以避免这个问题。

**Comment by hnzyc** [comment]
好像是可以在后台自动运行的。对，我再开个虚拟机挂一下，同时挂，可以节约点儿时间，太棒了

**Comment by hysbeta** [comment]
挂几个号没问题的，但是同一个号似乎不能同时上不同的课。
如果胆子大的把这三句的注释删掉 有些课应该可以直接跳过。。。
showExam(true);
delCookie("playState");
addCourseWarePlayRecord();

**Comment by hnzyc** [comment]
已经很知足了

**Comment by hnzyc** [comment]
试了下倍速播放，超过3倍播就不行了，提示看视频时长不够，估计网站有防倍速播放的监控

**Comment by ganfangbao** [comment]
今年视频后台记录时长，跳过了也不能考试，有没有什么办法？

**Comment by hysbeta** [comment]
> 今年视频后台记录时长，跳过了也不能考试，有没有什么办法？

我今年还没开始上课。。。可能要再等等
