### ISSUE TITLE
华医网无法跳过

### ISSUE THREAD

**Issue by zzgpku** [hysbeta/91huayi#6]
官网好像更新了，又跳不过去了，求大大更新~~

**Comment by hysbeta** [comment]
据其他人反应应该是不能直接跳了，要记录观看时间。
今年我的课还没开始上，晚点再修。。。

**Comment by lovingzyz** [comment]
> 据其他人反应应该是不能直接跳了，要记录观看时间。 今年我的课还没开始上，晚点再修。。。

求大佬早点修复，我们那已经开始专线了，又臭又长，好烦人

**Comment by zzgpku** [comment]
> 据其他人反应应该是不能直接跳了，要记录观看时间。 今年我的课还没开始上，晚点再修。。。

但在控制台里面看，好像没有发送记录时间的请求。

**Comment by hysbeta** [comment]
不能跳过了，但是现在可以稳定的挂公需课了。。
